version: "3.9"
services:
  pentaho:
    build: ./project
    volumes:
      - ./data:/opt/data
      - ./project:/opt/project
    environment:
      - DISPLAY=172.20.75.251:0
      - APP_ENV="prod"
      - APP_DEBUG="False"
      - APP_PORT=5000
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_HOSTNAME=${MONGODB_HOSTNAME}
    command: ["/opt/pentaho/spoon.sh"]
    privileged: true
    depends_on:
      - mongodb

  mssql:
    build: ./database
    volumes:
      - database_data_savvy:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=${MSSQL_PID}
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_DB=mydb
    ports:
      - 1433:1433

  mongodb:
    image: mongo:4.0.8
    restart: unless-stopped
    command: mongod --auth
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=mymongodb
      - MONGODB_DATA_DIR=/data/db
      - MONDODB_LOG_DIR=/dev/null
    volumes:
      - mongodbdata_savvy:/data/db
    networks:
      - mongo-compose-network

  mongo-express:
    image: mongo-express
    environment:
        - ME_CONFIG_MONGODB_SERVER=mongodb
        - ME_CONFIG_MONGODB_PORT=27017
        - ME_CONFIG_MONGODB_ENABLE_ADMIN=False
        - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
        - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_ROOT_USER}
        - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_ROOT_PASSWORD}
        - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
        - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
    depends_on:
        - mongodb
    ports:
    - "8081:8081"
    networks:
      - mongo-compose-network

volumes:
  database_data_savvy:
  mongodbdata_savvy:

networks:
  mongo-compose-network:
    driver: bridge
  # docker run --name sql_server_demo -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=1Secure*Password1' -e 'MSSQL_PID=Enterprise' -p 1433:1433 -d microsoft/mssql-server-linux:2017-latest
  #
  #
